import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import React from "react";

export default function Motor() {
  const [post, setPost] = React.useState(null);

  React.useEffect(() => {
    axios
      .get(`https://testexpressjsiot.herokuapp.com/subscribers`)
      .then((data) => {
        const dataList = data.data;
        setPost(dataList);
      })
      .catch((err) => {
        console.log(err);
        return err;
      });
  }, []);
  let no = 0;
  if (!post) return null;
  console.log(post);
  return (
    <div className={styles.container}>
      <Head>
        <title>Test JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        {post.map((data) => {
          return (
            <table key={data.id} className="table mt-5">
              <thead key={data.id}>
                <tr key={data.id}>
                  <th key={data.id} scope="col">
                    Sensor1
                  </th>
                  <th key={data.id} scope="col">
                    Sensor2
                  </th>
                  <th key={data.id} scope="col">
                    Sensor3
                  </th>
                  <th key={data.id} scope="col">
                    Sensor4
                  </th>
                  <th key={data.id} scope="col">
                    Sensor5
                  </th>
                  <th key={data.id} scope="col">
                    Sensor6
                  </th>
                  <th key={data.id} scope="col">
                    Sensor7
                  </th>
                  <th key={data.id} scope="col">
                    Sensor8
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr key={data.id}>
                  {data.baris1.map((datasensor) => {
                    return <td key={datasensor.id}>{datasensor}</td>;
                  })}
                </tr>
                <tr>
                  {data.baris2.map((datasensor) => {
                    return <td key={datasensor.id}>{datasensor}</td>;
                  })}
                </tr>
                <tr key={data.id}>
                  {data.baris3.map((datasensor) => {
                    return <td key={datasensor.id}>{datasensor}</td>;
                  })}
                </tr>
                <tr key={data.id}>
                  {data.baris4.map((datasensor) => {
                    return <td key={datasensor.id}>{datasensor}</td>;
                  })}
                </tr>
                <tr key={data.id}>
                  {data.baris5.map((datasensor) => {
                    return <td key={datasensor.id}>{datasensor}</td>;
                  })}
                </tr>
                <tr key={data.id}>
                  {data.baris6.map((datasensor) => {
                    return <td key={datasensor.id}>{datasensor}</td>;
                  })}
                </tr>
                <tr key={data.id}>
                  {data.baris7.map((datasensor) => {
                    return <td key={datasensor.id}>{datasensor}</td>;
                  })}
                </tr>
                <tr key={data.id}>
                  {data.baris8.map((datasensor) => {
                    return <td key={datasensor.id}>{datasensor}</td>;
                  })}
                </tr>
              </tbody>
            </table>
          );
        })}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
